name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Deploy to Rocky Linux 9
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/repos/weather-web
          git pull origin main
          yarn install --frozen-lockfile
          yarn build
          cp -r dist/* /var/www/fc.supulime.com/
          sudo systemctl restart nginx
